spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/myannadata
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=psql@07

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile


twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.phone.number=+918328343693
twilio.whatsapp-number=whatsapp:+14155238886


#spring.security.user.name:admin
#spring.security.user.password:admin123


spring.data.redis.host=localhost
spring.data.redis.port=6379

#spring.datasource.url=jdbc:mysql://localhost:3306/myannadata
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=root